stages:
    - install
    - build
    - test

image: node:latest

cache:
    paths:
        - local: '/P3/node_modules/'

install:
    stage: install
    script: 
        - npm ci

build:
    stage: build
    script:
        - npm run build
    artifacts:
        name: "lib"
        paths:
            - local: '/P3/lib/.js'
            - local: '/P3/lib/.d.ts'
