stages:
    - install
    - build
    - test

image: node:latest

cache:
    paths:
        - node_modules/

install:
    stage: install
    script: 
        - npm ci

build:
    stage: build
    script:
        - npx tsc
        - npm run build
