stages:
    - install
    - build
    - test

image: node:latest

cache:
    paths: 
        - P3/node_modules/

install:
    stage: install
    script: npm ci

build:
    stage: build
    script: npm run build
    artifacts:
        name: "lib"
        paths:
            - P3/lib/*.js
            - P3/lib/*.d.ts

lint:
    stage: test
    script: npm run lint

test:
    stage: test
    script: npm run test
    coverage: '/Code coverage: \d+\.\d+/'
    artifacts:
        name: "coverage"
        paths:
            - P3/coverage/*.html
        reports:
            junit:
                - P3/*.xml
