stages:
    - install
    - build
    - test

image: node:latest

cache:
    paths:
        - P3/node_modules/

install:
    stage: install
    script: 
        - npm ci

build:
    stage: build
    script:
        - npm run build
    artifacts:
        name: "lib"
        paths:
            - P3/lib/*.js
            - P3/lib/*.d.ts
