# three stages: install, build, test
stages:
    - install
    - build
    - test

# use Docker image node:latest
image: node:latest

# cache directory node_modules for all jobs
cache:
    paths: 
        - P3/node_modules/

# job install
install:
    stage: install
    # install dependencies of ts-elevator
    script: npm ci

# job build
build:
    stage: build
    # compiles TypeScript source code to JavaScript
    script: npm run build
    # saves *.js and *.d.ts files as artifact "lib"
    artifacts:
        name: "lib"
        paths:
            - P3/lib/*.js
            - P3/lib/*.d.ts

# job lint
lint:
    stage: test
    # execute linter
    script: npm run lint

# job test
test:
    stage: test
    # execute tests
    script: npm run test
    # regex for extracting total test coverage for all files
    coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
    # save HTML coverage report as artifact "coverage"
    # report test-results.xml to GitLab
    artifacts:
        name: "coverage"
        paths:
            - P3/coverage/*.html
        reports:
            junit: P3/*.xml
