stages:
    - install
    - build
    - test

image: node:latest

cache:
    paths:
        - node_modules/

install:
    stage: install
    script: 
        - npm ci

build:
    stage: build
    before_script:
        - npm install typescript
    script:
        - npm run build
    artifacts:
        name: "lib"
        paths:
            - .js
            - .d.ts
