stages:
    - install
    - build
    - test

default:
    image: node:latest
    
    before_script: 
        - bundle exec

install:
    stage: install
    cache:
        paths:
            - node_modules/
    script: 
        - npm ci

test:
    stage: test
    script:
        - npm run test
