stages:
    - install
    - build
    - test

default:
    image: node:latest
    
    before_script: 
        - bundle exec

install:
    stage: install
    cache:
        paths:
            - node_modules/
    script: 
        - npm ci

build:
    stage: build
    script:
        - docker run node npm run build

lint:
    stage: test
    script:
        - docker run node npm run lint

test:
    stage: test
    script:
        - docker run node npm run test
    artifacts:
        reports:
            junit:
                - test-results.xml
